# Site settings
title: Iran University of Science and Technology (IUST)
course_name: Project Management
course_description: "Project Management"
course_semester: "Second Semester Academic Year 1997-1998"
description: "Advanced topics in Design and Construction Project Management"
Instructor: Hoda Homayouni Ph.D.

message: Join our Telegram group <a href="https://t.me/joinchat/B73pJkrOWP_FwVba5pUhqg">groups page</a> to get notified about course announcements and add your weekly feedbacks.
baseurl: "/pm97" # the subpath of your site, e.g. /blog/
url: "http://hoda-homayouni.github.io/pm97" # the base hostname & protocol for your site
githubdir: "username/repo"

# Author/user information



address: |
    School of Architecture
    Iran University of Science and Technology
    Tehran, Iran


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"



plugins:
    - jekyll-jalali
